
The base dimension of your u-net should ideally be no smaller than 128, as recommended by a professional DDPM trainer https://nonint.com/2022/05/04/friends-dont-let-friends-train-small-diffusion-models/
Epoch 1/8
--- Unet 1 ---
<torch.utils.data.dataloader.DataLoader object at 0x7fc4658e42e0>






































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































Train Step 1000/40736 --- Loss: 0.0273 unet 2 has not been trained
when sampling, you can pass stop_at_unet_number to stop early in the cascade, so it does not try to generate with untrained unets
0it [00:00, ?it/s]


















































0it [01:40, ?it/s] step: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 999/1000 [01:40<00:00, 10.15it/s]
Traceback (most recent call last):
  File "/home/azureuser/imagen/spaceforge/train.py", line 271, in <module>
    run_train_loop(cfg, trainer, loader, device, i=cfg["train"]["unet_number"])
  File "/home/azureuser/imagen/spaceforge/train.py", line 146, in run_train_loop
    train(cfg, dataloader, trainer, epoch, unet_num, device)
  File "/home/azureuser/imagen/spaceforge/train.py", line 122, in train
    trainer.save(cfg["train"]["checkpoint_path"])
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/imagen_pytorch/trainer.py", line 691, in save
    with fs.open(path, 'wb') as f:
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/fsspec/spec.py", line 1009, in open
    f = self._open(
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/fsspec/implementations/local.py", line 155, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/fsspec/implementations/local.py", line 250, in __init__
    self._open()
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/fsspec/implementations/local.py", line 255, in _open
    self.f = open(self.path, mode=self.mode)
PermissionError: [Errno 13] Permission denied: '/datadrive4T/checkpoint/imagen_large_checkpoint.pt'